name: smart_home
description: A Smart Home application using Amazon Alexa

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.2.0
  flutter_carousel_slider: ^1.0.8
  font_awesome_flutter: ^9.2.0
  websafe_svg: ^2.1.0+1
  sleek_circular_slider: ^2.0.1
  lottie: ^1.2.1
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  speech_to_text: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/jpg/
    - assets/svg/
    - assets/lottie/
